"""
Post-hoc severity labeling for real (unlabeled) sensor data: Harespod and
the pilot altitude dataset. Neither dataset includes any AMS/HAPE/HACE
severity assessment (see harespod_loader.py and pilot_altitude_loader.py's
docstrings) -- they're just raw vitals streams. This module applies the
same clinically-motivated rules from docs/lls_mapping.md that
rule_baseline.py uses, so real data can be assigned a severity_label and
folded into the training set.

Reuses rule_baseline.classify_row() directly rather than re-deriving the
same thresholds here -- there is exactly one place in the codebase that
encodes "what spo2_delta/hr_elevation/trend combination means Severe AMS,"
and this module calls it rather than copying it, so the two can never
silently drift apart.

IMPORTANT -- this creates a real evaluation-integrity concern, not just a
technical detail: if a row's label was GENERATED by classify_row(), then
evaluating classify_row() (the rule baseline) against that same row is
circular -- it would trivially "predict" the label it produced. This is
why real, rule-labeled data is ONLY added to the TRAINING split
(feature_engineering.run_pipeline()) and never to val/test, which remain
100% synthetic (synthetic labels come from synth_data.py's own
TIER_PREVALENCE-driven generation, not from classify_row(), so no
circularity there). See feature_engineering.py's merge_real_data_for_training()
for where this boundary is enforced.

A documented alternative (not implemented, per project owner's request to
note it rather than build it): real data could instead be split across
train/val/test like synthetic data, with run_comparison() filtering the
rule baseline's own evaluation to synthetic-only rows while still scoring
XGBoost/LSTM on the full mixed set. That would give the ML models a more
realistic (real-sensor-noise-inclusive) test distribution, at the cost of
a more complex, source-aware comparison function. Worth revisiting if the
project ever wants val/test to reflect real sensor noise characteristics
rather than purely synthetic noise -- see feature_engineering.py for the
current train-only boundary this would need to change.
"""

from __future__ import annotations

import pandas as pd

from src.config import SEVERITY_TIERS
from src.data.feature_engineering import engineer_features
from src.models.rule_baseline import classify_row


def label_real_dataframe(raw: pd.DataFrame) -> pd.DataFrame:
    """
    Take a tidy raw DataFrame from harespod_loader or pilot_altitude_loader
    (columns: timestamp, spo2, hr, altitude, subject_id, data_source -- see
    each loader's TIDY_COLUMNS) and return it with engineered features AND
    a severity_label / severity_index assigned per-row via the rule-based
    thresholds.

    Must engineer features BEFORE labeling, since classify_row() needs
    spo2_delta and spo2_trend_5min, which only exist after
    engineer_features() has run -- unlike synthetic data, which is labeled
    at GENERATION time (the tier drives what values get generated), real
    data has to be labeled AFTER we know what its trend/delta features
    look like.

    Processes one subject at a time (same reasoning as
    feature_engineering.build_processed_dataset: rolling windows must never
    blend two subjects' readings together), re-attaching subject_id/
    data_source after engineer_features() since it doesn't preserve them.
    """
    frames = []
    for subject_id, group in raw.groupby("subject_id"):  # one subject at a time -- see docstring on why rolling windows can't cross subjects
        result = engineer_features(group)
        result["subject_id"] = subject_id  # engineer_features() doesn't carry this column through, so re-attach it from the groupby key
        if "data_source" in group.columns:
            result["data_source"] = group["data_source"].iloc[0]  # same re-attachment, constant per group so .iloc[0] is enough
        frames.append(result)
    featured = pd.concat(frames, ignore_index=True)

    # .apply(..., axis=1) runs classify_row() once per row (slower than a
    # vectorized formula, but this only runs on real data at load time, not
    # in a hot loop, and classify_row()'s branching logic isn't easily
    # vectorized) -- reusing the exact same rule function rule_baseline.py
    # itself evaluates against, per the module docstring's circularity note.
    severity_index = featured.apply(
        lambda row: classify_row(row["spo2_delta"], row["hr"], row["spo2_trend_5min"]),
        axis=1,
    )
    featured["severity_index"] = severity_index
    featured["severity_label"] = severity_index.map(dict(enumerate(SEVERITY_TIERS)))  # int index -> human-readable tier name, e.g. 2 -> "Severe AMS"

    return featured
